# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataConvertor(object):
    def setupUi(self, DataConvertor):
        DataConvertor.setObjectName("DataConvertor")
        DataConvertor.resize(603, 686)
        self.gridLayout_3 = QtWidgets.QGridLayout(DataConvertor)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(DataConvertor)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_source_nstm = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_source_nstm.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tool/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_source_nstm.setIcon(icon)
        self.pushButton_source_nstm.setFlat(True)
        self.pushButton_source_nstm.setObjectName("pushButton_source_nstm")
        self.gridLayout.addWidget(self.pushButton_source_nstm, 1, 2, 1, 1)
        self.lineEdit_source_nstm = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_source_nstm.setReadOnly(True)
        self.lineEdit_source_nstm.setObjectName("lineEdit_source_nstm")
        self.gridLayout.addWidget(self.lineEdit_source_nstm, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.pushButton_sink_nstm = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_sink_nstm.setText("")
        self.pushButton_sink_nstm.setIcon(icon)
        self.pushButton_sink_nstm.setFlat(True)
        self.pushButton_sink_nstm.setObjectName("pushButton_sink_nstm")
        self.gridLayout.addWidget(self.pushButton_sink_nstm, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit_sink_nstm = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sink_nstm.setReadOnly(True)
        self.lineEdit_sink_nstm.setObjectName("lineEdit_sink_nstm")
        self.gridLayout.addWidget(self.lineEdit_sink_nstm, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 1, 1, 1)
        self.listWidget_nstm = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_nstm.setObjectName("listWidget_nstm")
        self.gridLayout.addWidget(self.listWidget_nstm, 8, 1, 1, 2)
        self.pushButton_do_nstm = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_do_nstm.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_do_nstm.setObjectName("pushButton_do_nstm")
        self.gridLayout.addWidget(self.pushButton_do_nstm, 6, 1, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(DataConvertor)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_source_spc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_source_spc.setReadOnly(True)
        self.lineEdit_source_spc.setObjectName("lineEdit_source_spc")
        self.gridLayout_2.addWidget(self.lineEdit_source_spc, 1, 0, 1, 1)
        self.pushButton_do_spc = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_do_spc.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_do_spc.setObjectName("pushButton_do_spc")
        self.gridLayout_2.addWidget(self.pushButton_do_spc, 7, 0, 1, 2)
        self.pushButton_sink_spc = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_sink_spc.setText("")
        self.pushButton_sink_spc.setIcon(icon)
        self.pushButton_sink_spc.setFlat(True)
        self.pushButton_sink_spc.setObjectName("pushButton_sink_spc")
        self.gridLayout_2.addWidget(self.pushButton_sink_spc, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.pushButton_source_spc = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_source_spc.setText("")
        self.pushButton_source_spc.setIcon(icon)
        self.pushButton_source_spc.setFlat(True)
        self.pushButton_source_spc.setObjectName("pushButton_source_spc")
        self.gridLayout_2.addWidget(self.pushButton_source_spc, 1, 1, 1, 1)
        self.listWidget_spc = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_spc.setObjectName("listWidget_spc")
        self.gridLayout_2.addWidget(self.listWidget_spc, 9, 0, 1, 2)
        self.lineEdit_sink_spc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_sink_spc.setReadOnly(True)
        self.lineEdit_sink_spc.setObjectName("lineEdit_sink_spc")
        self.gridLayout_2.addWidget(self.lineEdit_sink_spc, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(DataConvertor)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_4.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 2)

        self.retranslateUi(DataConvertor)
        QtCore.QMetaObject.connectSlotsByName(DataConvertor)

    def retranslateUi(self, DataConvertor):
        _translate = QtCore.QCoreApplication.translate
        DataConvertor.setWindowTitle(_translate("DataConvertor", "Data Convertor"))
        self.groupBox.setTitle(_translate("DataConvertor", "OLD2NSTM"))
        self.label_3.setText(_translate("DataConvertor", "Path to save .nstm"))
        self.label.setText(_translate("DataConvertor", "Path to open old files"))
        self.label_2.setText(_translate("DataConvertor", "Converted data list:"))
        self.pushButton_do_nstm.setText(_translate("DataConvertor", "Do it"))
        self.groupBox_2.setTitle(_translate("DataConvertor", "OLD2SPC"))
        self.pushButton_do_spc.setText(_translate("DataConvertor", "Do it"))
        self.label_6.setText(_translate("DataConvertor", "Converted data list:"))
        self.label_5.setText(_translate("DataConvertor", "Path to save .spc"))
        self.label_4.setText(_translate("DataConvertor", "Path to open old files"))
        self.groupBox_3.setTitle(_translate("DataConvertor", "How to use it"))
        self.textBrowser_2.setHtml(_translate("DataConvertor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:10pt; font-weight:600; color:#000000;\">OLD2NSTM</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:10pt; font-weight:600; color:#000000;\">-------------------------</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:10pt; color:#000000;\">Convert old topography to .nstm file.<br />This converts all files in the folder to .nstm, assuming that they are topography.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:10pt; color:#000000;\">The old files usually have no suffix.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">1. select path to open old files</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">2. select path to save .nstm</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">3. click do it</span><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#000000;\">OLD2SPC</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#000000;\">-------------------------</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">Convert old spectra to .spc file.<br />This converts single spectra to .spc, assuming it has </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#ff0000;\">6</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\"> channels:<br />I forward, I backward, didv fwd, didv bws, IETS fwd, IETS bwd.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">All these 6 files should be in the same folder.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">The old spectra can be .txt, .dat, .exp.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\"><br />1. select file of the </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#ff0000;\">first channel</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\"> ( I forward)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">2. select path to save .spc</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">3. click do it</span></p></body></html>"))
import logo_rc
