# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapWin(object):
    def setupUi(self, MapWin):
        MapWin.setObjectName("MapWin")
        MapWin.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(MapWin)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = GraphicsLayoutWidget(MapWin)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.retranslateUi(MapWin)
        QtCore.QMetaObject.connectSlotsByName(MapWin)

    def retranslateUi(self, MapWin):
        _translate = QtCore.QCoreApplication.translate
        MapWin.setWindowTitle(_translate("MapWin", "Make a map"))
from pyqtgraph import GraphicsLayoutWidget
