# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvancedAlgebra.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvancedAlgebra(object):
    def setupUi(self, AdvancedAlgebra):
        AdvancedAlgebra.setObjectName("AdvancedAlgebra")
        AdvancedAlgebra.setWindowModality(QtCore.Qt.WindowModal)
        AdvancedAlgebra.resize(237, 151)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/data/calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdvancedAlgebra.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(AdvancedAlgebra)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(AdvancedAlgebra)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_lines = QtWidgets.QLabel(self.widget)
        self.label_lines.setObjectName("label_lines")
        self.gridLayout.addWidget(self.label_lines, 1, 0, 1, 2)
        self.lineEdit_adv = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_adv.setText("")
        self.lineEdit_adv.setReadOnly(False)
        self.lineEdit_adv.setClearButtonEnabled(True)
        self.lineEdit_adv.setObjectName("lineEdit_adv")
        self.gridLayout.addWidget(self.lineEdit_adv, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(AdvancedAlgebra)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_do_adv = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_do_adv.setObjectName("pushButton_do_adv")
        self.gridLayout_2.addWidget(self.pushButton_do_adv, 0, 0, 1, 1)
        self.pushButton_cancel_adv = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_cancel_adv.setObjectName("pushButton_cancel_adv")
        self.gridLayout_2.addWidget(self.pushButton_cancel_adv, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)

        self.retranslateUi(AdvancedAlgebra)
        QtCore.QMetaObject.connectSlotsByName(AdvancedAlgebra)

    def retranslateUi(self, AdvancedAlgebra):
        _translate = QtCore.QCoreApplication.translate
        AdvancedAlgebra.setWindowTitle(_translate("AdvancedAlgebra", "Advanced Algebra"))
        self.label_lines.setText(_translate("AdvancedAlgebra", "Lines:"))
        self.pushButton_do_adv.setText(_translate("AdvancedAlgebra", "Do it"))
        self.pushButton_cancel_adv.setText(_translate("AdvancedAlgebra", "Cancel"))
import logo_rc
