# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plot2D3D.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plot2D3D(object):
    def setupUi(self, Plot2D3D):
        Plot2D3D.setObjectName("Plot2D3D")
        Plot2D3D.resize(670, 413)
        self.gridLayout_3 = QtWidgets.QGridLayout(Plot2D3D)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(Plot2D3D)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_interval = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_interval.setObjectName("spinBox_interval")
        self.gridLayout.addWidget(self.spinBox_interval, 0, 1, 1, 1)
        self.slider_interval = QtWidgets.QSlider(self.widget_2)
        self.slider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.slider_interval.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_interval.setTickInterval(5)
        self.slider_interval.setObjectName("slider_interval")
        self.gridLayout.addWidget(self.slider_interval, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Plot2D3D)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(Plot2D3D)
        QtCore.QMetaObject.connectSlotsByName(Plot2D3D)

    def retranslateUi(self, Plot2D3D):
        _translate = QtCore.QCoreApplication.translate
        Plot2D3D.setWindowTitle(_translate("Plot2D3D", "Plot 2D/3D"))
        self.label.setText(_translate("Plot2D3D", "Interval: "))
