# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeightedAVG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeightedAVG(object):
    def setupUi(self, WeightedAVG):
        WeightedAVG.setObjectName("WeightedAVG")
        WeightedAVG.resize(629, 422)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/data/bear_and_beehive_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WeightedAVG.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(WeightedAVG)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(WeightedAVG)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 400))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_source = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_source.setObjectName("listWidget_source")
        self.gridLayout.addWidget(self.listWidget_source, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(WeightedAVG)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(WeightedAVG)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser_delPasses = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_delPasses.setObjectName("textBrowser_delPasses")
        self.gridLayout_2.addWidget(self.textBrowser_delPasses, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 1, 1, 1)

        self.retranslateUi(WeightedAVG)
        QtCore.QMetaObject.connectSlotsByName(WeightedAVG)

    def retranslateUi(self, WeightedAVG):
        _translate = QtCore.QCoreApplication.translate
        WeightedAVG.setWindowTitle(_translate("WeightedAVG", "Weighted AVG"))
        self.groupBox.setTitle(_translate("WeightedAVG", "Please select data:"))
        self.groupBox_2.setTitle(_translate("WeightedAVG", "Selected data:"))
        self.groupBox_3.setTitle(_translate("WeightedAVG", "Deleted passes:"))
import logo_rc
