# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvancedAlgebra_.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvancedAlgebra_(object):
    def setupUi(self, AdvancedAlgebra_):
        AdvancedAlgebra_.setObjectName("AdvancedAlgebra_")
        AdvancedAlgebra_.resize(444, 248)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdvancedAlgebra_.sizePolicy().hasHeightForWidth())
        AdvancedAlgebra_.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/data/sea-lion-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdvancedAlgebra_.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(AdvancedAlgebra_)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(AdvancedAlgebra_)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(AdvancedAlgebra_)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_do_adv = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_do_adv.setObjectName("pushButton_do_adv")
        self.gridLayout_2.addWidget(self.pushButton_do_adv, 0, 0, 1, 1)
        self.pushButton_cancel_adv = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_cancel_adv.setObjectName("pushButton_cancel_adv")
        self.gridLayout_2.addWidget(self.pushButton_cancel_adv, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(AdvancedAlgebra_)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_data = QtWidgets.QLabel(self.widget_3)
        self.label_data.setText("")
        self.label_data.setObjectName("label_data")
        self.gridLayout_4.addWidget(self.label_data, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 1, 1)

        self.retranslateUi(AdvancedAlgebra_)
        QtCore.QMetaObject.connectSlotsByName(AdvancedAlgebra_)

    def retranslateUi(self, AdvancedAlgebra_):
        _translate = QtCore.QCoreApplication.translate
        AdvancedAlgebra_.setWindowTitle(_translate("AdvancedAlgebra_", "Advanced Algebra"))
        self.pushButton_do_adv.setText(_translate("AdvancedAlgebra_", "Do it"))
        self.pushButton_cancel_adv.setText(_translate("AdvancedAlgebra_", "Exit"))
        self.label.setText(_translate("AdvancedAlgebra_", "Selected Data:"))
import logo_rc
