# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataSlicing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_DataSlicing(object):
    def setupUi(self, DataSlicing):
        pg.setConfigOption('background', (240, 240, 240, 255))
        pg.setConfigOption('foreground', 'k')
        DataSlicing.setObjectName("DataSlicing")
        DataSlicing.resize(1167, 512)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/data/pack_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataSlicing.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DataSlicing)
        self.centralwidget.setObjectName("centralwidget")
        DataSlicing.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DataSlicing)
        self.statusbar.setObjectName("statusbar")
        DataSlicing.setStatusBar(self.statusbar)

        self.retranslateUi(DataSlicing)
        QtCore.QMetaObject.connectSlotsByName(DataSlicing)

    def retranslateUi(self, DataSlicing):
        _translate = QtCore.QCoreApplication.translate
        DataSlicing.setWindowTitle(_translate("DataSlicing", "Data Slicing"))
import logo_rc
