# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataSelection(object):
    def setupUi(self, DataSelection):
        DataSelection.setObjectName("DataSelection")
        DataSelection.resize(829, 422)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/data/shark_and_lollipop_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataSelection.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(DataSelection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(DataSelection)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 400))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_source = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_source.setObjectName("listWidget_source")
        self.gridLayout.addWidget(self.listWidget_source, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(DataSelection)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)

        self.retranslateUi(DataSelection)
        QtCore.QMetaObject.connectSlotsByName(DataSelection)

    def retranslateUi(self, DataSelection):
        _translate = QtCore.QCoreApplication.translate
        DataSelection.setWindowTitle(_translate("DataSelection", "Data Selection"))
        self.groupBox.setTitle(_translate("DataSelection", "Please select data:"))
        self.groupBox_2.setTitle(_translate("DataSelection", "Selected data:"))
import logo_rc
