# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Illumination.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Illumination(object):
    def setupUi(self, Illumination):
        Illumination.setObjectName("Illumination")
        Illumination.resize(422, 506)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/data/light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Illumination.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Illumination)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = GraphicsLayoutWidget(Illumination)
        self.graphicsView.setMinimumSize(QtCore.QSize(400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Illumination)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_phi = QtWidgets.QSlider(self.widget)
        self.slider_phi.setMaximum(360)
        self.slider_phi.setProperty("value", 90)
        self.slider_phi.setOrientation(QtCore.Qt.Horizontal)
        self.slider_phi.setObjectName("slider_phi")
        self.gridLayout.addWidget(self.slider_phi, 3, 2, 1, 1)
        self.spinBox_phi = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_phi.sizePolicy().hasHeightForWidth())
        self.spinBox_phi.setSizePolicy(sizePolicy)
        self.spinBox_phi.setReadOnly(True)
        self.spinBox_phi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_phi.setMaximum(360)
        self.spinBox_phi.setProperty("value", 90)
        self.spinBox_phi.setObjectName("spinBox_phi")
        self.gridLayout.addWidget(self.spinBox_phi, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_theta = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_theta.sizePolicy().hasHeightForWidth())
        self.spinBox_theta.setSizePolicy(sizePolicy)
        self.spinBox_theta.setReadOnly(True)
        self.spinBox_theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_theta.setMaximum(90)
        self.spinBox_theta.setProperty("value", 45)
        self.spinBox_theta.setObjectName("spinBox_theta")
        self.gridLayout.addWidget(self.spinBox_theta, 0, 1, 1, 1)
        self.slider_theta = QtWidgets.QSlider(self.widget)
        self.slider_theta.setMaximum(90)
        self.slider_theta.setProperty("value", 45)
        self.slider_theta.setOrientation(QtCore.Qt.Horizontal)
        self.slider_theta.setObjectName("slider_theta")
        self.gridLayout.addWidget(self.slider_theta, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(Illumination)
        QtCore.QMetaObject.connectSlotsByName(Illumination)

    def retranslateUi(self, Illumination):
        _translate = QtCore.QCoreApplication.translate
        Illumination.setWindowTitle(_translate("Illumination", "Illumination"))
        self.label_2.setText(_translate("Illumination", "φ"))
        self.label.setText(_translate("Illumination", "θ"))
from pyqtgraph import GraphicsLayoutWidget
import logo_rc
